name: Deploy to Firebase

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm install
        cd functions && npm install
    
    - name: Build React app
      env:
        CI: false
        GENERATE_SOURCEMAP: false
      run: npm run build
    
    - name: Deploy to Firebase Hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KYUYOPRINT }}'
        projectId: kyuyoprint
        channelId: live
    
    - name: Deploy Firestore Rules and Indexes
      env:
        GOOGLE_APPLICATION_CREDENTIALS_JSON: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KYUYOPRINT }}'
      run: |
        echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > $HOME/gcloud-service-key.json
        export GOOGLE_APPLICATION_CREDENTIALS="$HOME/gcloud-service-key.json"
        npx firebase-tools deploy --only firestore:rules,firestore:indexes --project kyuyoprint --non-interactive
    
    - name: Deploy Firebase Functions
      env:
        GOOGLE_APPLICATION_CREDENTIALS_JSON: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KYUYOPRINT }}'
      run: |
        echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > $HOME/gcloud-service-key.json
        export GOOGLE_APPLICATION_CREDENTIALS="$HOME/gcloud-service-key.json"
        npx firebase-tools deploy --only functions --project kyuyoprint --non-interactive 