name: Deploy to Firebase

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm install
        cd functions && npm install
    
    - name: Build React app
      env:
        CI: false
        GENERATE_SOURCEMAP: false
      run: npm run build
    
    - name: Deploy to Firebase
      run: |
        # Create service account file safely
        echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > service-account.json
        
        # Set up authentication
        export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/service-account.json"
        
        # Install older, more stable version of firebase-tools
        npm install -g firebase-tools@10.9.2
        
        # Deploy step by step to isolate any issues
        firebase deploy --only hosting --project kyuyoprint --non-interactive
        firebase deploy --only firestore:rules,firestore:indexes --project kyuyoprint --non-interactive
        
        # Try functions deploy (comment out if it continues to fail)
        firebase deploy --only functions --project kyuyoprint --non-interactive || echo "Functions deploy failed, but continuing..."
        
        # Clean up
        rm service-account.json 